# Generated by Django 4.0.4 on 2024-01-29 20:53

import django.contrib.auth.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Llanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_clave', models.CharField(blank=True, max_length=100, null=True, verbose_name='Producto/Clave')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
                ('existencia', models.IntegerField(default=0, verbose_name='Existencia')),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo Promedio Pesos')),
                ('ancho', models.CharField(blank=True, max_length=10, null=True, verbose_name='Ancho')),
                ('alto', models.CharField(blank=True, max_length=10, null=True, verbose_name='Alto')),
                ('rin', models.CharField(blank=True, max_length=10, null=True, verbose_name='Rin')),
                ('marca', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Llanta',
                'verbose_name_plural': 'Llantas',
                'db_table': 'Llanta',
                'ordering': ['producto_clave'],
            },
            bases=(models.Model, django.contrib.auth.mixins.PermissionRequiredMixin),
        ),
    ]
