# Generated by Django 4.0.4 on 2024-01-31 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llanta',
            name='producto_clave',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Producto/Clave'),
        ),
    ]
