# Generated by Django 4.0.4 on 2024-01-31 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_llanta_producto_clave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llanta',
            name='producto_clave',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Producto/Clave'),
        ),
        migrations.AlterUniqueTogether(
            name='llanta',
            unique_together={('producto_clave',)},
        ),
    ]
