# Generated by Django 4.0.4 on 2024-06-19 21:40

import core.models
import django.contrib.auth.mixins
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
                'db_table': 'Bitcora',
                'ordering': ['-creado'],
            },
            bases=(models.Model, django.contrib.auth.mixins.PermissionRequiredMixin),
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon', models.CharField(max_length=100, verbose_name='Razon')),
                ('giro', models.CharField(max_length=100, verbose_name='Giro')),
                ('esquema', models.JSONField(verbose_name='Esquema')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'Empresa',
                'ordering': ['razon'],
            },
            bases=(models.Model, django.contrib.auth.mixins.PermissionRequiredMixin),
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familia', models.CharField(max_length=100, verbose_name='Familia')),
                ('idSubfamilia', models.IntegerField(default=0, verbose_name='Id Subfamilia')),
                ('subFamilia', models.CharField(max_length=100, verbose_name='Subfamilia')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Familia',
                'verbose_name_plural': 'Familias',
                'db_table': 'Familia',
                'ordering': ['familia', 'subFamilia'],
            },
            bases=(models.Model, django.contrib.auth.mixins.PermissionRequiredMixin),
        ),
        migrations.CreateModel(
            name='Llanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_clave', models.CharField(blank=True, max_length=100, null=True, verbose_name='Producto/Clave')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
                ('existencia', models.IntegerField(default=0, verbose_name='Existencia')),
                ('costo_promedio_pesos', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo Promedio Pesos')),
                ('tipo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo')),
                ('subtipo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Subtipo')),
                ('capas', models.IntegerField(default=0, verbose_name='Capas')),
                ('precio_especia_llantashop_pago_efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Especia LLANTASHOP pago Efectivo')),
                ('msi_3', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='3 MSI')),
                ('msi_6', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='6 MSI')),
                ('msi_9', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='9 MSI')),
                ('msi_12', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='12 MSI')),
                ('msi_18', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='18 MSI')),
                ('envio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Envio')),
                ('utilidad', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Utilidad')),
                ('afiliado', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Afiliado')),
                ('actualizado', models.IntegerField(default=1, verbose_name='Actualizado en el proceso de extracción')),
                ('ancho', models.CharField(blank=True, max_length=10, null=True, verbose_name='Ancho')),
                ('alto', models.CharField(blank=True, max_length=10, null=True, verbose_name='Alto')),
                ('rin', models.CharField(blank=True, max_length=10, null=True, verbose_name='Rin')),
                ('radial', models.IntegerField(default=0, verbose_name='Radial')),
                ('marca', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Llanta',
                'verbose_name_plural': 'Llantas',
                'db_table': 'Llanta',
                'ordering': ['producto_clave'],
            },
            bases=(models.Model, django.contrib.auth.mixins.PermissionRequiredMixin),
        ),
        migrations.CreateModel(
            name='MensajePicky',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Token')),
                ('number', models.CharField(max_length=50, verbose_name='Number')),
                ('message_in', models.CharField(max_length=255, verbose_name='Mensage in')),
                ('message_in_raw', models.CharField(max_length=255, verbose_name='Mensaje in raw')),
                ('message', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mensaje')),
                ('application', models.CharField(blank=True, max_length=255, null=True, verbose_name='Aplicación')),
                ('tipo', models.CharField(default=2, max_length=255, verbose_name='Type')),
                ('unique_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Unique id')),
                ('quoted', models.CharField(blank=True, max_length=255, null=True, verbose_name='Quoted')),
                ('estatus_mensaje', models.IntegerField(choices=[(0, 'Terminado'), (1, 'Activo')], default=1, verbose_name='Estatus del mensaje')),
                ('nivel', models.IntegerField(default=1, verbose_name='Nivel de pregunta')),
                ('opcion1', models.JSONField(blank=True, null=True, verbose_name='Acción')),
                ('opcion2', models.JSONField(blank=True, null=True, verbose_name='Bien')),
                ('opcion3', models.JSONField(blank=True, null=True, verbose_name='Estado')),
                ('opcion4', models.JSONField(blank=True, null=True, verbose_name='Municipio')),
                ('opcion5', models.JSONField(blank=True, null=True, verbose_name='Bien seleccionado')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Mensaje picky',
                'verbose_name_plural': 'Mensajes picky',
                'db_table': 'MensajePicky',
                'ordering': ['number', '-creado'],
            },
            bases=(models.Model, django.contrib.auth.mixins.PermissionRequiredMixin),
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(default='Correo', max_length=255, verbose_name='Correo suscripción')),
            ],
            options={
                'verbose_name': 'Correo',
                'verbose_name_plural': 'Correos',
                'db_table': 'Suscripcion',
                'ordering': ['correo'],
                'unique_together': {('correo',)},
            },
            bases=(models.Model, django.contrib.auth.mixins.PermissionRequiredMixin),
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_clave', models.CharField(blank=True, max_length=100, null=True, verbose_name='Producto/Clave')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
                ('existencia', models.IntegerField(default=0, verbose_name='Existencia')),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo')),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio')),
                ('caracteristicas', models.JSONField(blank=True, null=True, verbose_name='Caracteristicas')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('familia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProdFam', to='core.familia')),
                ('subFamilia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProdSFam', to='core.familia')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'Producto',
                'ordering': ['producto_clave'],
            },
            bases=(models.Model, django.contrib.auth.mixins.PermissionRequiredMixin),
        ),
        migrations.CreateModel(
            name='CaracProm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambito', models.IntegerField(choices=[(1, 'toda la tienda'), (2, 'Familia'), (3, 'Familia Subfamilia'), (4, 'Producto')], default=4, verbose_name='Ámbito')),
                ('cveProm', models.IntegerField(choices=[(1, 'Meses sin intereses'), (2, 'Meses con intereses'), (3, 'Descuento en pago en efectivo'), (4, 'Llevate X y pago Y')], default=4, verbose_name='Cve. Promocion')),
                ('descProm', models.CharField(max_length=255, verbose_name='Descripción promoción')),
                ('tipo', models.IntegerField(choices=[(1, 'Porcentaje'), (2, 'Importe'), (3, 'Cantidad')], default=4, verbose_name='Cve. Promocion')),
                ('valor1', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Valor 1')),
                ('valor2', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Valor 2')),
                ('vigenciaInicio', models.DateField(default=django.utils.timezone.now, verbose_name='Inicio vigencia')),
                ('vigenciaFin', models.DateField(default=core.models.default_vigencia_fin, verbose_name='Fin vigencia')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('familia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caracPromFam', to='core.familia')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caracPromProd', to='core.producto')),
                ('subFamilia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caracPromSFam', to='core.familia')),
            ],
            options={
                'verbose_name': 'Caracterica pago',
                'verbose_name_plural': 'Caracteristicas pago',
                'db_table': 'CaracProd',
                'ordering': ['ambito', 'cveProm'],
            },
            bases=(models.Model, django.contrib.auth.mixins.PermissionRequiredMixin),
        ),
    ]
