# Generated by Django 4.0.4 on 2023-05-18 00:51

import django.contrib.auth.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Llanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_clave', models.CharField(blank=True, max_length=100, null=True, verbose_name='Producto/Clave')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
                ('existencia', models.IntegerField(default=0, verbose_name='Existencia')),
                ('costo_promedio_pesos', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo Promedio Pesos')),
                ('tipo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo')),
                ('subtipo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Subtipo')),
                ('capas', models.IntegerField(default=0, verbose_name='Capas')),
                ('precio_especia_llantashop_pago_efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Especia LLANTASHOP pago Efectivo')),
                ('msi_3', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='3 MSI')),
                ('msi_6', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='6 MSI')),
                ('msi_9', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='9 MSI')),
                ('msi_12', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='12 MSI')),
                ('msi_18', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='18 MSI')),
                ('envio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ENVIO')),
                ('utilidad', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='UTILIDAD')),
                ('afiliado', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='AFILIADO')),
                ('actualizado', models.IntegerField(default=1, verbose_name='Actualizado')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Llanta',
                'verbose_name_plural': 'Llantas',
                'db_table': 'Llanta',
                'ordering': ['producto_clave'],
            },
            bases=(models.Model, django.contrib.auth.mixins.PermissionRequiredMixin),
        ),
    ]
