# Generated by Django 4.0.4 on 2024-06-25 19:34

import django.contrib.auth.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Descripción',
                'verbose_name_plural': 'Descripciones',
                'db_table': 'Detalle',
                'ordering': ['descripcion'],
                'unique_together': {('descripcion',)},
            },
            bases=(models.Model, django.contrib.auth.mixins.PermissionRequiredMixin),
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField(default=1, verbose_name='Nivel')),
                ('titulo', models.CharField(default='Sin título', max_length=30, verbose_name='Título')),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Precio')),
                ('sinPrecio', models.CharField(blank=True, max_length=150, null=True, verbose_name='Texto sin precio')),
                ('estatus', models.CharField(choices=[(0, 'Baja'), (1, 'Activo')], default='1', max_length=1, verbose_name='Estatus')),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
                'db_table': 'Promocion',
                'ordering': ['nivel'],
                'unique_together': {('nivel',)},
            },
            bases=(models.Model, django.contrib.auth.mixins.PermissionRequiredMixin),
        ),
        migrations.AlterField(
            model_name='mensajepicky',
            name='estatus_mensaje',
            field=models.IntegerField(choices=[('0', 'Terminado'), ('1', 'Activo')], default=1, verbose_name='Estatus del mensaje'),
        ),
        migrations.CreateModel(
            name='PromocionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorX', models.CharField(blank=True, max_length=20, null=True, verbose_name='Valor XXXX')),
                ('valorY', models.CharField(blank=True, max_length=20, null=True, verbose_name='Valor YYYY')),
                ('incluido', models.BooleanField(default=True, verbose_name='Incluido')),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.detalle')),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.promocion')),
            ],
            options={
                'verbose_name': 'Promoción-Detalle',
                'verbose_name_plural': 'Promociones-Detalles',
                'db_table': 'PromocionDetalle',
                'ordering': ['promocion', 'detalle'],
                'unique_together': {('promocion', 'detalle')},
            },
        ),
    ]
