# Generated by Django 4.0.4 on 2024-06-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_detalle_promocion_alter_mensajepicky_estatus_mensaje_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='estatus',
            field=models.CharField(choices=[('0', 'Baja'), ('1', 'Activo')], default='1', max_length=1, verbose_name='Estatus'),
        ),
    ]
