# Generated by Django 4.0.4 on 2024-06-25 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_promocion_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='promociondetalle',
            name='renglon',
            field=models.IntegerField(default=0, verbose_name='Renglón'),
        ),
    ]
