# Generated by Django 4.0.4 on 2024-06-19 00:10

import core.models
import django.contrib.auth.mixins
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_llanta_alto_alter_llanta_ancho_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon', models.CharField(max_length=100, verbose_name='Razon')),
                ('giro', models.CharField(max_length=100, verbose_name='Giro')),
                ('esquema', models.JSONField(verbose_name='Esquema')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'Empresa',
                'ordering': ['razon'],
            },
            bases=(models.Model, django.contrib.auth.mixins.PermissionRequiredMixin),
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familia', models.CharField(max_length=100, verbose_name='Familia')),
                ('idSubfamilia', models.IntegerField(default=0, verbose_name='Id Subfamilia')),
                ('subFamilia', models.CharField(max_length=100, verbose_name='Subfamilia')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Familia',
                'verbose_name_plural': 'Familias',
                'db_table': 'Familia',
                'ordering': ['familia', 'subFamilia'],
            },
            bases=(models.Model, django.contrib.auth.mixins.PermissionRequiredMixin),
        ),
        migrations.AlterModelOptions(
            name='bitacora',
            options={'ordering': ['-creado'], 'verbose_name': 'Registro', 'verbose_name_plural': 'Registros'},
        ),
        migrations.AlterModelOptions(
            name='mensajepicky',
            options={'ordering': ['number', '-creado'], 'verbose_name': 'Mensaje picky', 'verbose_name_plural': 'Mensajes picky'},
        ),
        migrations.RemoveField(
            model_name='bitacora',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='mensajepicky',
            name='fecha_alta',
        ),
        migrations.AddField(
            model_name='bitacora',
            name='creado',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado'),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='modificado',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
        migrations.AddField(
            model_name='mensajepicky',
            name='creado',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado'),
        ),
        migrations.AddField(
            model_name='mensajepicky',
            name='modificado',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_clave', models.CharField(blank=True, max_length=100, null=True, verbose_name='Producto/Clave')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
                ('existencia', models.IntegerField(default=0, verbose_name='Existencia')),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo')),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio')),
                ('caracteristicas', models.JSONField(blank=True, null=True, verbose_name='Caracteristicas')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('familia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProdFam', to='core.familia')),
                ('subFamilia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProdSFam', to='core.familia')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'Producto',
                'ordering': ['producto_clave'],
            },
            bases=(models.Model, django.contrib.auth.mixins.PermissionRequiredMixin),
        ),
        migrations.CreateModel(
            name='CaracProm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambito', models.IntegerField(choices=[(1, 'toda la tienda'), (2, 'Familia'), (3, 'Familia Subfamilia'), (4, 'Producto')], default=4, verbose_name='Ámbito')),
                ('cveProm', models.IntegerField(choices=[(1, 'Meses sin intereses'), (2, 'Meses con intereses'), (3, 'Descuento en pago en efectivo'), (4, 'Llevate X y pago Y')], default=4, verbose_name='Cve. Promocion')),
                ('descProm', models.CharField(max_length=255, verbose_name='Descripción promoción')),
                ('tipo', models.IntegerField(choices=[(1, 'Porcentaje'), (2, 'Importe'), (3, 'Cantidad')], default=4, verbose_name='Cve. Promocion')),
                ('valor1', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Valor 1')),
                ('valor2', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Valor 2')),
                ('vigenciaInicio', models.DateField(default=django.utils.timezone.now, verbose_name='Inicio vigencia')),
                ('vigenciaFin', models.DateField(default=core.models.default_vigencia_fin, verbose_name='Fin vigencia')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('familia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caracPromFam', to='core.familia')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caracPromProd', to='core.producto')),
                ('subFamilia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caracPromSFam', to='core.familia')),
            ],
            options={
                'verbose_name': 'Caracterica pago',
                'verbose_name_plural': 'Caracteristicas pago',
                'db_table': 'CaracProd',
                'ordering': ['ambito', 'cveProm'],
            },
            bases=(models.Model, django.contrib.auth.mixins.PermissionRequiredMixin),
        ),
    ]
