# Generated by Django 4.0.4 on 2024-06-25 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_promociondetalle_renglon'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='promociondetalle',
            unique_together={('promocion', 'detalle', 'renglon')},
        ),
    ]
