# Generated by Django 4.0.4 on 2024-06-25 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_promociondetalle_incluido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promociondetalle',
            options={'ordering': ['promocion', 'renglon'], 'verbose_name': 'Promoción-Detalle', 'verbose_name_plural': 'Promociones-Detalles'},
        ),
        migrations.AlterUniqueTogether(
            name='promociondetalle',
            unique_together={('promocion', 'renglon')},
        ),
    ]
