# Generated by Django 4.0.4 on 2024-01-31 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_alter_cotizacion_vigencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='vigencia',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 31, 19, 32, 38, 71970), verbose_name='Vigencia'),
        ),
    ]
