# Generated by Django 4.0.4 on 2024-01-31 23:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0005_alter_cotizacion_vigencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='correo_electronico',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='vigencia',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 31, 23, 53, 42, 969538), verbose_name='Vigencia'),
        ),
    ]
