# Generated by Django 4.0.4 on 2024-02-06 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0006_cotizacion_correo_electronico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='vigencia',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 6, 17, 41, 44, 961602), verbose_name='Vigencia'),
        ),
    ]
