# Generated by Django 4.0.4 on 2024-02-07 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0007_alter_cotizacion_vigencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='vigencia',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 7, 16, 49, 58, 136482), verbose_name='Vigencia'),
        ),
    ]
