# Generated by Django 4.0.4 on 2024-02-07 21:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0008_alter_cotizacion_vigencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='vigencia',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 7, 21, 45, 18, 905327), verbose_name='Vigencia'),
        ),
    ]
