# Generated by Django 4.0.4 on 2024-02-07 22:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0010_alter_cotizacion_vigencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='vigencia',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 7, 22, 48, 45, 697757), verbose_name='Vigencia'),
        ),
    ]
