# Generated by Django 4.0.4 on 2024-02-08 00:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0014_alter_cotizacion_vigencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='vigencia',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 8, 0, 30, 40, 675960), verbose_name='Vigencia'),
        ),
    ]
