# Generated by Django 4.0.4 on 2024-02-08 00:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0015_alter_cotizacion_vigencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='vigencia',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 8, 0, 44, 43, 725207), verbose_name='Vigencia'),
        ),
    ]
