# Generated by Django 4.0.4 on 2024-01-30 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajepicky',
            name='opcion6',
            field=models.JSONField(blank=True, null=True, verbose_name='Llantas'),
        ),
        migrations.AddField(
            model_name='mensajepicky',
            name='opcion7',
            field=models.JSONField(blank=True, null=True, verbose_name='Envio'),
        ),
        migrations.AddField(
            model_name='mensajepicky',
            name='opcion8',
            field=models.JSONField(blank=True, null=True, verbose_name='Correo'),
        ),
        migrations.AddField(
            model_name='mensajepicky',
            name='opcion9',
            field=models.JSONField(blank=True, null=True, verbose_name='Adicional'),
        ),
    ]
